name: test Action
on: [push]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - run: php test/main.php

